version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: artwork-pg
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - ./../postgres-db:/var/lib/postgresql/data

  python:
    build:
      context: ./artwork_api
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    ports:
      - '8000:8000'
    links:
      - postgres
    depends_on:
      - postgres

  portfolio-page:
    build:
      context: ./portfolio-page
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:80"
volumes:
  postgres-db: